version: '3.8'
services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    ports:
      - "5959:5959"
      - "5958:5958"
    environment:
      - PYTHON_PORT=5959
      - HOST=0.0.0.0
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
      - DATABASE_URL=${DATABASE_URL}
